title: Google Sheets Guide
description: Cours et atelier pratique Google Sheets
baseurl: "https://silahi.github.io/google-sheet/" # si repo sur https://username.github.io/repo-name/
url: "https://silahi.github.io/google-sheet/"
theme: architect # th√®me Jekyll Architect
markdown: kramdown
